const TYPES = ['topBun','bottomBun','patty','doublePatty','cheese','lettuce','tomato','bacon','pickle','onion','egg','sauce'];
const recipes = [
 ['bottomBun','patty','cheese','lettuce','tomato','topBun'],['bottomBun','patty','bacon','cheese','topBun'],['bottomBun','doublePatty','cheese','pickle','topBun'],['bottomBun','patty','egg','bacon','topBun'],['bottomBun','lettuce','tomato','onion','patty','topBun'],['bottomBun','patty','sauce','pickle','onion','topBun'],['bottomBun','doublePatty','cheese','bacon','lettuce','topBun'],['bottomBun','patty','tomato','lettuce','sauce','topBun'],['bottomBun','patty','cheese','onion','pickle','topBun'],['bottomBun','bacon','patty','egg','cheese','topBun'],['bottomBun','doublePatty','cheese','cheese','topBun'],['bottomBun','lettuce','patty','tomato','bacon','topBun'],['bottomBun','patty','pickle','sauce','tomato','topBun'],['bottomBun','cheese','patty','lettuce','egg','topBun'],['bottomBun','patty','onion','bacon','sauce','topBun'],['bottomBun','doublePatty','lettuce','tomato','cheese','topBun'],['bottomBun','patty','cheese','pickle','bacon','topBun'],['bottomBun','egg','patty','lettuce','tomato','topBun'],['bottomBun','patty','sauce','onion','cheese','topBun'],['bottomBun','doublePatty','bacon','egg','topBun'],['bottomBun','lettuce','patty','cheese','tomato','topBun'],['bottomBun','patty','pickle','egg','bacon','topBun']
];
const state={score:0,lives:3,level:1,recipe:[],step:0,chefX:50,active:false,last:-1,spawnTimer:null};
const $=s=>document.querySelector(s), zone=$('#fallingZone'), chef=$('#chef');
function sprite(type,cls='ingredient'){const e=document.createElement('div');e.className=cls;e.dataset.type=type;return e}
function chooseRecipe(){let i;do{i=Math.floor(Math.random()*recipes.length)}while(i===state.last);state.last=i;return recipes[i]}
function drawCard(){const stack=$('#recipeStack');stack.replaceChildren(...state.recipe.map(x=>sprite(x)));$('#orderNo').textContent='#'+String(state.level).padStart(2,'0')}
function updateHud(){ $('#score').textContent=String(state.score).padStart(4,'0');$('#lives').textContent='♥ '.repeat(state.lives).trim()||'—';$('#level').textContent=String(state.level).padStart(2,'0') }
function announce(){const names={bottomBun:'pan inferior',topBun:'pan superior',patty:'carne',doublePatty:'doble carne',cheese:'queso',lettuce:'lechuga',tomato:'tomate',bacon:'tocineta',pickle:'pepinillos',onion:'cebolla',egg:'huevo',sauce:'salsa'};$('#instruction').textContent=`Siguiente: ${names[state.recipe[state.step]]}`}
function newLevel(){state.recipe=chooseRecipe();state.step=0;state.active=false;drawCard();updateHud();$('#recipeCard').className='recipe-card center';$('#instruction').textContent='¡Memoriza la receta!';setTimeout(()=>{$('#recipeCard').className='recipe-card corner';announce();state.active=true;spawnLoop()},5000)}
function spawnLoop(){clearTimeout(state.spawnTimer);if(!state.active)return;spawnIngredient();state.spawnTimer=setTimeout(spawnLoop,950)}
function spawnIngredient(){let type;const expected=state.recipe[state.step];type=Math.random()<.42?expected:TYPES[Math.floor(Math.random()*TYPES.length)];const e=sprite(type,'ingredient falling');e.style.left=(8+Math.random()*82)+'%';e.style.setProperty('--rot',`${-12+Math.random()*24}deg`);e.style.setProperty('--duration',(4.2+Math.random()*1.8)+'s');e.addEventListener('animationend',()=>e.remove());e.addEventListener('click',()=>catchIngredient(e));zone.append(e)}
function catchIngredient(el){if(!state.active||!el.isConnected)return;el.remove();const got=el.dataset.type;if(got===state.recipe[state.step]){state.score+=40;state.step++;if(state.step===state.recipe.length)complete();else announce()}else{state.lives--;flash('#e8543e');if(state.lives<=0)gameOver()}updateHud()}
function flash(color){$('#kitchen').animate([{filter:'none'},{filter:`drop-shadow(0 0 25px ${color})`},{filter:'none'}],{duration:320})}
function complete(){state.active=false;clearTimeout(state.spawnTimer);state.score+=250;updateHud();const assembly=$('#assembly');assembly.replaceChildren(...state.recipe.map((x,i)=>{let a=sprite(x);a.style.animationDelay=(i*.17)+'s';return a}));assembly.className='assembly show';setTimeout(()=>{$('#bonus').textContent=250;$('#overlay').classList.remove('hidden')},state.recipe.length*170+450);setTimeout(()=>{$('#overlay').classList.add('hidden');assembly.className='assembly';state.level++;newLevel()},state.recipe.length*170+2300)}
function gameOver(){state.active=false;clearTimeout(state.spawnTimer);$('#instruction').textContent='¡Se acabaron las vidas!';setTimeout(()=>{state.score=0;state.lives=3;state.level=1;newLevel()},1400)}
function move(dir){if(!state.active)return;state.chefX=Math.max(5,Math.min(92,state.chefX+dir*5));chef.style.left=`calc(${state.chefX}% - 44px)`;const cr=chef.getBoundingClientRect();[...zone.children].forEach(e=>{const r=e.getBoundingClientRect();if(r.bottom>cr.top+18&&r.top<cr.bottom&&r.left<cr.right&&r.right>cr.left)catchIngredient(e)})}
addEventListener('keydown',e=>{if(['ArrowLeft','a','A'].includes(e.key))move(-1);if(['ArrowRight','d','D'].includes(e.key))move(1)});$('#startBtn').onclick=()=>{$('#startScreen').classList.add('hidden');newLevel()};
